name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout repository
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "requirements.txt not found"; exit 1; fi
    - name: Lint with flake8
      run: |
        flake8 . --max-line-length=100 --exclude=venv --count --statistics --output-file=flake8-report.txt
    - name: Test with pytest
      run: |
        pytest tests/ --verbose --junitxml=pytest-report.xml --html=pytest-report.html --self-contained-html
    - name: Upload Flake8 report
      uses: actions/upload-artifact@v4
      with:
        name: flake8-report
        path: flake8-report.txt
    - name: Upload Pytest report
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: pytest-report.html